/* Generated by re2c 1.0.1 on Thu Nov  8 15:18:21 2018 */
#line 1 "fstream.re"
/*
 * compile with: 
 * re2c --input custom -o fstream.cc fstream.re
 * g++ -o fstream fstream.cc
 */

#include <cstdio>
#include <fstream>

enum Token {
    INTEGER,
    STRING,
    ID,
    OTHER,
    END
};

void print_token(Token token) {
    switch(token) {
        case Token::ID:
            printf("toke id\n");
        default:
            printf("other\n");
    }
}

static Token lex(std::ifstream &in)
{
    std::streampos mar;
#   define YYCTYPE     char
#   define YYPEEK()    in.peek()
#   define YYSKIP()    do { in.ignore(); if (in.eof()) return Token::END; } while(0)
#   define YYBACKUP()  mar = in.tellg()
#   define YYRESTORE() in.seekg(mar)

    
#line 40 "fstream.cc"
{
	YYCTYPE yych;
	yych = YYPEEK ();
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy4;
	default:	goto yy2;
	}
yy2:
	YYSKIP ();
#line 39 "fstream.re"
	{ return Token::OTHER; }
#line 104 "fstream.cc"
yy4:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy4;
	default:	goto yy6;
	}
yy6:
#line 40 "fstream.re"
	{ return Token::INTEGER; }
#line 177 "fstream.cc"
}
#line 41 "fstream.re"

}

int main(int argc, char **argv)
{
    //std::ifstream in(stdin, std::ios::binary);
    //if (in.fail()) return 2;

    Token token = Token::OTHER;
    do {
        token = lex(stdin);
        print_token(token);
    } while(token != Token::END);

    return 0;
}
