language: cpp
# faster container-based travis
sudo: false

compiler:
 - gcc
 - clang

# preinstalled packages
addons:
  apt:
    packages:
    - bison
    - python3-docutils

# in-tree and out-of-tree builds
env:
 - BUILD_DIR=re2c       CONFIG_DIR=.
 - BUILD_DIR=re2c-build CONFIG_DIR=../re2c/

script:
  - cd re2c && ./autogen.sh
  - cd ..
  - mkdir -p $BUILD_DIR && cd $BUILD_DIR
  - |
    $CONFIG_DIR/configure \
        --prefix="$(pwd)"/re2c-install \
        --enable-docs
  - make -j$(nproc)
  - make -j$(nproc) check VERBOSE=1
  - make -j$(nproc) install
